name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  ci:
    name: Test and Update DB
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: web-app-template-test
          POSTGRES_PASSWORD: pwd
          POSTGRES_USER: postgres
        ports:
          - 5433:5432
    env:
      ENVIRONMENT: development
      PORT: 8080
      POSTGRES_URL: postgresql://postgres:pwd@localhost:5433/web-app-template-test
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun format-check
      - run: bun lint
      - run: bun typecheck
      - run: bun test
      - run: bun e2e
      - run: bun drizzle
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
