name: Terraform

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/tf.yml"

permissions:
  id-token: write

defaults:
  run:
    working-directory: terraform

jobs:
  terraform:
    name: Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: ${{ secrets.ACTIONS_IAM_ROLE }}

      - name: Create State Bucket
        run: |
          if aws s3api head-bucket --bucket "${BUCKET_NAME}" 2>/dev/null
          then
            echo "Bucket exists: $BUCKET_NAME"
          else
            echo "Bucket does not exist, creating: ${BUCKET_NAME}"
            aws s3 mb s3://"${BUCKET_NAME}"
          fi
        env:
          BUCKET_NAME: web-app-template-terraform-us-east-2

      - name: Setup
        uses: hashicorp/setup-terraform@v2

      - name: Init
        run: terraform init

      - name: Validate
        run: terraform validate -no-color

      - name: Apply
        run: terraform apply -auto-approve
